#HI ILYA BILYA ILY ILYA BILYA NOTICE ME ILYA PLEASEEE ILYA BILYA
import turtle as t
t.speed(0)
#tulip!!!

#stem
t.setheading(270)
t.penup()
t.forward(50)
t.pencolor("darkgreen")
t.left(180)
t.pendown()
t.pensize(5)
t.forward(100)
#leaf
t.fillcolor('lightgreen')
t.begin_fill()
t.left(70)
t.circle(50,43)
t.left(120) 	
t.circle(50,43)
t.end_fill()
#petals
t.fillcolor("orange")
t.left(82)
t.forward(75)
t.pencolor("orange")
t.right(90)
t.penup()
t.pendown()
t.begin_fill()
t.circle(50,-90)
t.left(40)
t.forward(30)
t.left(120)
t.forward(30)
t.setheading(0)
t.forward(30)
t.right(70)
t.forward(30)
t.setheading(0)
t.left(75)
t.forward(30)
t.setheading(95)
t.circle(63,-60)
t.end_fill()

wn = t.Screen()
wn.mainloop()
